openapi: 3.0.0
info:
  title: Socialapp API
  description: Our first Social app at XYZ - Arjun.
  version: 1.0.1

servers:
  - url: http://localhost:3000/api/v1
    description: Localhost version of our app
  - url: https://localhost:3000/api/v1
    description: This is just a dummy version of API, it does not work.

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /instagram:
    get:
      summary:  returns username, followers and follows
      responses:
        "200": # status code
          description: returns an object
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  followers:
                    type: string
                  follows:
                    type: string
  /{token}:
    get:
      summary:  returns whichever is there in parameters
      parameters:
        - name: token
          default: 5
          in: path
          schema:
            type: string
      responses:
        "200": # status code
          description: returns an object
          content:
            application/json:
              schema:
                type: object
                properties:
                  params:
                    type: string